services:
  db:
    image: postgres:latest
    container_name: splatoon-db
    environment:
      POSTGRES_DB: splatoon
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: splatoon-api
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.dev
    volumes:
      - ./alembic/versions:/code/alembic/versions
    restart: unless-stopped

volumes:
  postgres_data: